version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - static_data:/app/app/static
      - analysis_results:/app/analysis_results
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: python -m app.main
    restart: unless-stopped

volumes:
  static_data:
  analysis_results: 